### ISSUE TITLE
Tendermint consensus should not start until miner/worker.start() is called

### ISSUE THREAD

**Issue by qizhou** [QuarkChain/go-ethereum#40]
This prevents the consensus engine runs the consensus sync too early

**Comment by blockchaindevsh** [comment]
I moved tm.Init to worker.newWorkLoop so that tm consensus only starts after miner/worker.start is called, together with changes related with stress test: https://github.com/QuarkChain/go-ethereum/pull/36

**Comment by qizhou** [comment]
Fixed in #36
